# Generated by Django 5.1 on 2025-03-08 21:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_name', models.CharField(max_length=32, verbose_name='Toplantı Adı')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Toplantı Tarihi')),
                ('meeting_file', models.FileField(blank=True, null=True, upload_to='meeting_files/', verbose_name='Toplantı Dosyası')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to='entity.employee')),
                ('parent_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.meeting')),
            ],
            options={
                'verbose_name': 'Toplantı',
                'verbose_name_plural': 'Toplantılar',
            },
        ),
        migrations.CreateModel(
            name='Attendants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attended_meetings', to='entity.employee')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendants', to='entity.meeting')),
            ],
            options={
                'verbose_name': 'Toplantı Katılmcısı',
                'verbose_name_plural': 'Toplantı Katılımcıları',
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_text', models.TextField(default='Varsayılan gündem metni', verbose_name='Gündem Maddesi')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='entity.meeting')),
            ],
            options={
                'verbose_name': 'Toplantının Gündem Maddesi',
                'verbose_name_plural': 'Toplantının Gündem Maddeleri',
            },
        ),
        migrations.CreateModel(
            name='Decisions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('decision_status', models.TextField(choices=[('finalized', 'Karar Kesinleşti'), ('pending', 'Karar Kesinleşmedi'), ('cancelled', 'Karar İptal Edildi'), ('completed_later', 'Sonradan Tamamlandı'), ('cancelled_later', 'Sonradan İptal Edildi')], default='pending', verbose_name='Durum')),
                ('topic_group', models.CharField(max_length=64, verbose_name='Konu Grubu')),
                ('decision_text', models.TextField(default='Varsayılan karar metni', verbose_name='Karar Metni')),
                ('decision_taken_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Kararın Alınma Tarihi')),
                ('decision_finished_date', models.DateTimeField(blank=True, null=True, verbose_name='Kararın Tamamlanma Tarihi')),
                ('decision_finish_text', models.TextField(blank=True, null=True, verbose_name='Kararın Tamamlanma Yazısı')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='decision_evidence/', verbose_name='Kanıt Dosyası')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_decisions', to='entity.employee')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='entity.meeting')),
                ('meeting_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='entity.topics')),
            ],
            options={
                'verbose_name': 'Karar',
                'verbose_name_plural': 'Kararlar',
            },
        ),
    ]
